spring:
  application:
    name: mc-consumer
server:
  port: 9090


user:
  service:
    version: 1.0.0
dubbo:
  scan:
    base-packages: cn.bintools.daios.mcconsumer
  application:
    id: consumer
    name: consumer
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    serialization: kryo
  registry:
    id: zookeeper
    address: zookeeper://127.0.0.1:2181

